<template>
  <div class="lss-tab-con">
    <NavTag :title="'财务报表'"></NavTag>
    <div class="switch-ctrl lss-warp-div">
      <i-switch size="large" @on-change="changedSwitch" v-model="switchValue">
          <span slot="open">全开</span>
          <span slot="close">全关</span>
      </i-switch>
    </div>
    <Collapse v-model="value">
      <Panel v-for="(item,index) in tableData" :name="'1'+index" :key="index">
        {{ item.title }}
        <Row slot="content">
          <tableForm :financeId="index" :itemData="item.itemData" :itemTitle="item.itemTitle" :itemGS="item.itemGS"></tableForm>
        </Row>
      </Panel>
    </Collapse>
  </div>
</template>
<script>
    export default {
        name: "finance",
        data(){
            return {
              value:[10,11,12,13,14,15,16],
              switchValue:true,
              tableData:[
                {
                  title:"偿债能力分析",
                  loading:false,
                  itemTitle:{
                    "a":{
                      "name":"流动资产",
                      "val":0,
                      "test":416.54
                    },
                    "b":{
                      "name":"流动负债",
                      "val":0,
                      "test":867.34
                    },
                    "c":{
                      "name":"存货",
                      "val":0,
                      "test":217.12
                    },
                    "d":{
                      "name":"货币资金",
                      "val":0,
                      "test":83.73
                    },
                   /* "e":{
                      "name":"短期投资",
                      "val":0
                    },
                    "f":{
                      "name":"应收票据",
                      "val":0
                    },
                    "g":{
                      "name":"应收帐款",
                      "val":0
                    },
                    "h":{
                      "name":"销售收入",
                      "val":0
                    },
                    "i":{
                      "name":"平均应收账",
                      "val":0
                    }*/
                  },
                  itemData:[
                    {
                      "tableDate":"中国 ***",
                      "j":'82.17%',
                      "k":'55.70%',
                      //"l":'--',
                      "m":'23.51%',
                      //"n":'--',
                      //"o":'--',
                      //"p":'--'
                    },
                    {
                      "tableDate":'*** 地产',
                      "j":'52.75%',
                      "k":'47.85%',
                      //"l":'--',
                      "m":'7.33%',
                      //"n":'19.17%',
                      //"o":'--',
                      //"p":'--'
                    }/*,
                    {
                      "tableDate":"中国联通",
                      "j":'17.76%',
                      "k":'14.52%',
                      //"l":'--',
                      "m":'7.33%',
                      //"n":'19.17%',
                      //"o":'--',
                      //"p":'--'
                    },*/
                  ],
                  itemGS:{
                    "j":{
                      "name":"流动比率",
                      "jisuan":"流动资产／流动负债",
                      "js":'(this.itemTitle.a.val/this.itemTitle.b.val)*100'
                    },
                    "k":{
                      "name":"速动比率",
                      "jisuan":"（流动资产－存货）／流动负债",
                      "js":"((this.itemTitle.a.val-this.itemTitle.c.val)/this.itemTitle.b.val)*100"
                    },
                    /*"l":{
                      "name":"保守速动比率（超速动比率）",
                      "jisuan":"货币资金+短期投资+应收票据+应收帐款）／流动负债",
                      "js":"(this.itemTitle.d.val+this.itemTitle.e.val+this.itemTitle.f.val+this.itemTitle.g.val)/this.itemTitle.b.val"
                    },*/
                    "m":{
                      "name":"现金比率",
                      "jisuan":"（货币资金／流动负债）",
                      "js":"(this.itemTitle.d.val/this.itemTitle.b.val)*100"
                    },
                    /*"n":{
                      "name":"应收帐款周转率",
                      "jisuan":"销售收入／平均应收帐款",
                      "js":"this.itemTitle.h.val/this.itemTitle.i.val"
                    },
                    "o":{
                      "name":"应收帐款周转天数",
                      "jisuan":"360天／(销售收入／平均应收帐款)",
                      "js":"360/(this.itemTitle.h.val/this.itemTitle.i.val)"
                    },*/
                  }
                },
                {
                  title:"资本结构分析（或长期偿债能力分析）",
                  loading:false,
                  itemTitle:{
                    "a":{
                      "name":"股东权益总额",
                      "val":0,
                      "test":501.66
                    },
                    "b":{
                      "name":"资产总额",
                      "val":0,
                      "test":1465.11
                    },
                    "c":{
                      "name":"负债总额",
                      "val":0,
                      "test":963.45
                    },
                    /*"d":{
                      "name":"负债合计",
                      "val":0,
                      "test":0
                    },
                    "e":{
                      "name":"股东权益期末数",
                      "val":0,
                      "test":0
                    },
                    "f":{
                      "name":"长期负债",
                      "val":0,
                      "test":0
                    },
                    "g":{
                      "name":"短期借款",
                      "val":0,
                      "test":0
                    },
                    "h":{
                      "name":"一年内到期的长期负债",
                      "val":0,
                      "test":0
                    },
                    "i":{
                      "name":"长期借款",
                      "val":0,
                      "test":0
                    },
                    "j":{
                      "name":"应付债券",
                      "val":0,
                      "test":0
                    },
                    "k":{
                      "name":"长期应付款",
                      "val":0,
                      "test":0
                    },
                    "l":{
                      "name":"股东权益期末数",
                      "val":0,
                      "test":0
                    }*/
                  },
                  itemData:[
                    {
                      "tableDate":"中国 ***",
                      "j":"57.91%",
                      "k":'42.08%',
                      //"l":"321",
                      //"m":"23",
                      //"n":"673"
                    },
                    {
                      "tableDate":"*** 地产",
                      "j":"-209773.04%",
                      "k":'106.88%',
                      //"l":321,
                      //"m":23,
                      //"n":673
                    }/*,
                    {
                      "tableDate":"中国联通",
                      "j":"aa%",
                      "k":'58.29%',
                      //"l":"aa%",
                      //"m":"aa%",
                      //"n":"aa%"
                    }*/
                  ],
                  itemGS:{
                    "j":{
                      "name":"股东权益比率",
                      "jisuan":"股东权益总额／资产总额×100%",
                      "js":'(this.itemTitle.a.val/this.itemTitle.b.val)*100'
                    },
                    "k":{
                      "name":"资产负债比率",
                      "jisuan":"负债总额／资产总额×100%",
                      "js":'(this.itemTitle.c.val/this.itemTitle.b.val)*100'
                    },
                    /*"l":{
                      "name":"资本负债比率",
                      "jisuan":"负债合计／股东权益期末数×100%",
                      "js":'(this.itemTitle.d.val/this.itemTitle.e.val)*100'
                    },
                    "m":{
                      "name":"长期负载比率",
                      "jisuan":"长期负债／资产总额×100%",
                      "js":'(this.itemTitle.f.val/this.itemTitle.b.val)*100'
                    },
                    "n":{
                      "name":"有息负债比率",
                      "jisuan":"（短期借款＋一年内到期的长期负债＋长期借款＋应付债券＋长期应付款）／股东权益期末数×100%",
                      "js":'((this.itemTitle.g.val+this.itemTitle.h.val+this.itemTitle.i.val+this.itemTitle.j.val+this.itemTitle.k.val)/this.itemTitle.l.val)*100'
                    }*/
                  }
                },
                {
                  title:"经营效率分析",
                  loading:false,
                  itemTitle:{
                    "a":{
                      "name":"每股净资产",
                      "val":0,
                      "test":1.39
                    },
                    /*"b":{
                      "name":"股东权益",
                      "val":0,
                      "test":000
                    },
                    "c":{
                      "name":"３年以上的应收帐款",
                      "val":0,
                      "test":000
                    },
                    "d":{
                      "name":"待摊费用",
                      "val":0,
                      "test":000
                    },
                    "e":{
                      "name":"待处理财产净损失",
                      "val":0,
                      "test":000
                    },
                    "f":{
                      "name":"递延资产",
                      "val":0,
                      "test":000
                    },
                    "g":{
                      "name":" 普通股股数",
                      "val":0,
                      "test":000
                    },*/
                    "h":{
                      "name":"营业费用",
                      "val":0,
                      "test":106.08
                    },
                    "i":{
                      "name":"主营业务收入",
                      "val":0,
                      "test":129.87
                    },
                    "j":{
                      "name":"财务费用",
                      "val":0,
                      "test":6.9
                    },
                    /*"k":{
                      "name":"上期三项费用合计",
                      "val":0,
                      "test":000
                    },
                    "l":{
                      "name":"本期三项费用合计",
                      "val":0,
                      "test":000
                    },*/
                    "m":{
                      "name":"管理费用",
                      "val":0,
                      "test":3.66
                    },
                    /*"n":{
                      "name":"销货成本",
                      "val":0,
                      "test":000
                    },
                    "o":{
                      "name":"期初存货",
                      "val":0,
                      "test":000
                    },
                    "p":{
                      "name":"期末存货",
                      "val":0,
                      "test":000
                    },
                    "q":{
                      "name":"销售收入",
                      "val":0,
                      "test":000
                    },
                    "r":{
                      "name":"平均固定资产",
                      "val":0,
                      "test":000
                    },
                    "s":{
                      "name":"平均资产总额",
                      "val":0,
                      "test":000
                    },
                    "t":{
                      "name":"本期主营业务收入",
                      "val":0,
                      "test":000
                    },
                    "u":{
                      "name":"上期主营业务收入",
                      "val":0,
                      "test":000
                    },*/
                    "v":{
                      "name":"其他应收帐款",
                      "val":0,
                      "test":33.33
                    },
                    "w":{
                      "name":"流动资产",
                      "val":0,
                      "test":416.54
                    },
                    "y":{
                      "name":"调整后每股净资产",
                      "val":0,
                      "test":110
                    }
                  },
                  itemData:[
                    {
                      "tableDate":"中国 ***",
                      "a":"108.33%",
                      //"b":'1.38',
                      "c":"79.39%",
                      "d":"1.11%",
                      //"e":673,
                      "f":4547.51,
                      /*"g":323,
                      "h":323,
                      "i":323,
                      "j":'0.57%',
                      "k":'5.94%',*/
                      "l":"16.20%"
                    },
                    {
                      "tableDate":"*** 地产",
                      "a":'17600%',
                      //"b":'1.38',
                      "c":"121.28%",
                      "d":"39.35%",
                      //"e":673,
                      "f":8.12,
                      /*"g":323,
                      "h":323,
                      "i":323,
                      "j":'0.57%',
                      "k":'5.94%',*/
                      "l":"46.07%"
                    }
                  ],
                  itemGS:{
                    "a":{
                      "name":"净资产调整系数",
                      "jisuan":"（调整后每股净资产－每股净资产）/每股净资产",
                      "js":'((this.itemTitle.y.val-this.itemTitle.a.val)/this.itemTitle.a.val)*100'
                    },
                    /*"b":{
                      "name":"调整后每股净资产",
                      "jisuan":"（股东权益－３年以上的应收帐款－待摊费用－待处理财产净损失－递延资产）/ 普通股股数",
                      'js':"(this.itemTitle.b.val-this.itemTitle.c.val-this.itemTitle.d.val-this.itemTitle.e.val-this.itemTitle.f.val)/this.itemTitle.g.val"
                    },*/
                    "c":{
                      "name":"营业费用率",
                      "jisuan":"营业费用 / 主营业务收入×100%",
                      "js":'(this.itemTitle.h.val/this.itemTitle.i.val)*100'
                    },
                    "d":{
                      "name":"财务费用率",
                      "jisuan":"财务费用 / 主营业务收入×100%",
                      "js":'(this.itemTitle.j.val/this.itemTitle.i.val)*100'
                    },
                    /*"e":{
                      "name":"三项费用增长率",
                      "jisuan":"（上期三项费用合计－本期三项费用合计）/ 本期三项费用合计",
                      "js":"(this.itemTitle.k.val-this.itemTitle.l.val)/this.itemTitle.l.val"
                    },*/
                    "f":{
                      "name":"三项费用合计",
                      "jisuan":"营业费用＋管理费用＋财务费用",
                      "js":"this.itemTitle.h.val+this.itemTitle.m.val+this.itemTitle.j.val"
                    },
                    /*"g":{
                      "name":"存货周转率",
                      "jisuan":"销货成本×２／（期初存货＋期末存货）",
                      "js":"this.itemTitle.n.val*2/(this.itemTitle.o.val+this.itemTitle.p.val)"
                    },
                    "h":{
                      "name":"存货周转天数",
                      "jisuan":"３６０天／存货周转率",
                      "js":"360/(this.itemTitle.n.val*2/(this.itemTitle.o.val+this.itemTitle.p.val))"
                    },
                    "i":{
                      "name":"固定资产周转率",
                      "jisuan":"销售收入／平均固定资产",
                      "js":"this.itemTitle.q.val/this.itemTitle.r.val"
                    },
                    "j":{
                      "name":"总资产周转率",
                      "jisuan":"销售收入／平均资产总额",
                      "js":"this.itemTitle.q.val/this.itemTitle.s.val"
                    },
                    "k":{
                      "name":"主营业务收入增长率",
                      "jisuan":"（本期主营业务收入－上期主营业务收入）／上期主营业务收入×100%",
                      "js":'((this.itemTitle.t.val-this.itemTitle.u.val)/this.itemTitle.u.val)*100'
                    },*/
                    "l":{
                      "name":"其他应收帐款与流动资产比率",
                      "jisuan":"其他应收帐款／流动资产",
                      "js":"(this.itemTitle.v.val/this.itemTitle.w.val)*100"
                    }
                  }
                },
                /*{
                  title:"盈利能力分析",
                  loading:false,
                  itemTitle:{
                    "a":{
                      "name":"营业成本",
                      "val":0,
                      "test":106.08
                    },
                    "b":{
                      "name":"主营业务收入",
                      "val":0,
                      "test":129.87
                    },

                    "d":{
                      "name":"利润总额",
                      "val":0,
                      "test":0
                    },
                    "e":{
                      "name":"净利润",
                      "val":0,
                      "test":0
                    },

                    "h":{
                      "name":"净资产",
                      "val":0,
                      "test":0
                    },

                    "n":{
                      "name":"主营业务成本",
                      "val":0,
                      "test":106.08
                    }
                  },
                  itemData:[
                    {
                      "tableDate":"中国 ***",
                      "a":"79.39%",
                      "b":'--',
                      "c":'--',
                      "d":"2.8%",
                      "e":"673",
                      "f":'4.64%',
                      "g":"3823",
                      "h":"3623",
                      "i":'3.17%',
                      "j":"3423",
                      "k":"3923",
                      "l":"3"
                    },
                    {
                      "tableDate":"中国 ***",
                      "a":"79.39%",
                      "b":'--',
                      "c":'--',
                      "d":"2.8%",
                      "e":"673",
                      "f":'4.64%',
                      "g":"3823",
                      "h":"3623",
                      "i":'3.17%',
                      "j":"3423",
                      "k":"3923",
                      "l":"3"
                    },
                    {
                      "tableDate":"中国联通",
                      "a":"--%",
                      "b":'--%',
                      "c":'--%',
                      "d":"--%",
                      "e":"--%",
                      "f":'4.64%',
                      "g":"--%",
                      "h":"--%",
                      "i":'--%',
                      "j":"3.17%",
                      "k":"--%",
                      "l":"--%"
                    }
                  ],
                  itemGS:{
                    "a":{
                      "name":"营业成本比率",
                      "jisuan":"营业成本/主营业务收入×100%",
                      "js":'(this.itemTitle.a.val/this.itemTitle.b.val)*100'
                    },

                    "c":{
                      "name":"税前利润率",
                      "jisuan":"利润总额/主营业务收入×100%",
                      "js":'(this.itemTitle.d.val/this.itemTitle.b.val)*100'
                    },
                    "d":{
                      "name":"税后利润率",
                      "jisuan":"净利润/主营业务收入×100%",
                      "js":'(this.itemTitle.e.val/this.itemTitle.b.val)*100'
                    },

                    "f":{
                      "name":"净资产收益率",
                      "jisuan":" 净利润／净资产×100%",
                      "js":'(this.itemTitle.e.val/this.itemTitle.h.val)*100'
                    },

                    "l":{
                      "name":"销售毛利率",
                      "jisuan":"（主营业务收入－主营业务成本）／主营业务收入×100%",
                      "js":'((this.itemTitle.b.val-this.itemTitle.n.val)/this.itemTitle.b.val)*100'
                    }
                  }
                },
                {
                  title:"投资收益分析",
                  loading:false,
                  itemTitle:{
                    "a":{
                      "name":"每股市场价",
                      "val":0
                    },
                    "b":{
                      "name":"每股净利润",
                      "val":0
                    },
                    "c":{
                      "name":"每股净资产值",
                      "val":0
                    },
                    "d":{
                      "name":"每股资产值",
                      "val":0
                    }
                  },
                  itemData:[
                    {
                      "tableDate":2012,
                      "a":1,
                      "b":63,
                      "c":321
                    },
                    {
                      "tableDate":2012,
                      "a":61,
                      "b":263,
                      "c":721
                    }
                  ],
                  itemGS:{
                    "a":{
                      "name":"市盈率",
                      "jisuan":"每股市场价／每股净利润",
                      "js":'this.itemTitle.a.val/this.itemTitle.b.val'
                    },
                    "b":{
                      "name":"净资产倍率",
                      "jisuan":"每股市场价／每股净资产值",
                      "js":"this.itemTitle.a.val/this.itemTitle.c.val"
                    },
                    "c":{
                      "name":"资产倍率 ",
                      "jisuan":"每股市场价／每股资产值",
                      "js":"this.itemTitle.a.val/this.itemTitle.d.val"
                    }
                  }
                },
                {
                  title:"现金保障能力分析",
                  loading:false,
                  itemTitle:{
                    "a":{
                      "name":"销售商品、提供劳务收到的现金",
                      "val":0
                    },
                    "b":{
                      "name":"主营业务收入",
                      "val":0
                    },
                    "c":{
                      "name":"经营活动产生的现金流量净额",
                      "val":0
                    },
                    "d":{
                      "name":"净利润",
                      "val":0
                    },
                    "e":{
                      "name":"营业现金流量净额",
                      "val":0
                    },
                    "f":{
                      "name":"其他与经营活动有关的现金流入",
                      "val":0
                    },
                    "g":{
                      "name":"其他与经营活动有关的现金流出",
                      "val":0
                    },
                    "h":{
                      "name":"短期借款",
                      "val":0
                    },
                    "i":{
                      "name":"１年内到期的长期负债",
                      "val":0
                    },
                    "j":{
                      "name":"现金及现金等价物净增加额",
                      "val":0
                    },
                    "k":{
                      "name":"股数",
                      "val":0
                    },
                    "l":{
                      "name":"折旧及摊销",
                      "val":0
                    },
                    "m":{
                      "name":"资本支出",
                      "val":0
                    },
                    "n":{
                      "name":"流动资金需求",
                      "val":0
                    },
                    "o":{
                      "name":"偿还负债本金",
                      "val":0
                    },
                    "p":{
                      "name":"新借入资金",
                      "val":0
                    }
                  },
                  itemData:[
                    {
                      "tableDate":2012,
                      "a":1,
                      "b":63,
                      "c":321,
                      "d":61,
                      "e":263,
                      "f":721,
                      "g":21
                    }
                  ],
                  itemGS:{
                    "a":{
                      "name":"销售商品收到现金与主营业务收入比率",
                      "jisuan":"销售商品、提供劳务收到的现金／主营业务收入×100％",
                      "js":'(this.itemTitle.a.val/this.itemTitle.b.val)*100'
                    },
                    "b":{
                      "name":"经营活动产生的现金流量净额与净利润比率",
                      "jisuan":"经营活动产生的现金流量净额／净利润×100％",
                      "js":'(this.itemTitle.c.val/this.itemTitle.d.val)*100'
                    },
                    "c":{
                      "name":"净利润直接现金保障倍数",
                      "jisuan":"（营业现金流量净额－其他与经营活动有关的现金流入＋其他与经营活动有关的现金流出）/主营业务收入×100％",
                      "js":'((this.itemTitle.e.val-this.itemTitle.f.val+this.itemTitle.g.val)/this.itemTitle.b.val)*100'
                    },
                    "d":{
                      "name":"营业现金流量净额对短期有息负债比率",
                      "jisuan":"营业现金流量净额／（短期借款＋１年内到期的长期负债）×100％",
                      "js":'(this.itemTitle.e.val/(this.itemTitle.h.val+this.itemTitle.i.val))*100'
                    },
                    "e":{
                      "name":"每股现金及现金等价物净增加额",
                      "jisuan":"现金及现金等价物净增加额／股数",
                      "js":'this.itemTitle.j.val/this.itemTitle.k.val'
                    },
                    "f":{
                      "name":"每股自由现金流量",
                      "jisuan":"自由现金流量／股数",
                      "js":'(this.itemTitle.d.val+this.itemTitle.l.val-this.itemTitle.m.val-this.itemTitle.n.val-this.itemTitle.o.val+this.itemTitle.p.val)/this.itemTitle.k.val'
                    },
                    "g":{
                      "name":"自由现金流量",
                      "jisuan":"净利润＋折旧及摊销－资本支出－流动资金需求－偿还负债本金＋新借入资金",
                      "js":'this.itemTitle.d.val+this.itemTitle.l.val-this.itemTitle.m.val-this.itemTitle.n.val-this.itemTitle.o.val+this.itemTitle.p.val'
                    }
                  }
                },
                {
                  title:"利润构成分析",
                  loading:false,
                  itemTitle:{},
                  itemData:[],
                  itemGS:{}
                },*/
              ]
            }
        },
        methods:{
            changedSwitch:function(){
                if(this.switchValue){
                  this.value = [10,11,12,13,14,15];
                }else{
                  this.value = [];
                }
            },
        }
    }
</script>

<style scoped>
  .switch-ctrl {width: 100%; height: auto; overflow: hidden;text-align: right; padding:10px 0px;}
</style>
